---
robottelo_url: https://github.com/SatelliteQE/robottelo.git
robottelo_directory: /root/robottelo
robottelo_virtualenv_path: /root/robottelo/venv
robottelo_version: master
robottelo_junit_file: results.xml
robottelo_pytest_options: >
  tests/foreman/endtoend/test_api_endtoend.py::EndToEndTestCase::test_positive_end_to_end
robottelo_hostname: "{{ ansible_fqdn }}"
robottelo_ssh_username: root
robottelo_ssh_key: "/root/.ssh/id_rsa"
